CREATE TABLE IF NOT EXISTS `admin_exp` (
	`admin_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`uid` INTEGER NOT NULL UNIQUE,
	`department` VARCHAR(255) NOT NULL COMMENT '所属部门',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL COMMENT '更新时间',
	PRIMARY KEY(`admin_id`)
) COMMENT='管理员扩展信息';