CREATE TABLE IF NOT EXISTS `role` (
	`role_id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`role_name` VARCHAR(64) NOT NULL COMMENT '角色名称',
	`role_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '角色编码',
	`description` VARCHAR(256) NOT NULL COMMENT '角色描述',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	PRIMARY KEY(`role_id`)
) COMMENT='角色表';