CREATE TABLE IF NOT EXISTS `user_base` (
	`uid` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(64) NOT NULL UNIQUE COMMENT '登录用户名',
	`password` VARCHAR(128) NOT NULL COMMENT '登录密码',
	`gender` CHAR(1) COMMENT '性别',
	`phone` VARCHAR(32) COMMENT '联系电话',
	`email` VARCHAR(128) COMMENT '邮箱',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY(`uid`)
) COMMENT='用户基本字段表';