CREATE TABLE IF NOT EXISTS `user_role` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`uid` INTEGER NOT NULL COMMENT '用户id',
	`role_id` INTEGER NOT NULL COMMENT '角色id',
	PRIMARY KEY(`id`)
) COMMENT='用户-角色关联表';